services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - apache

  apache:
    build: ./apache

  ftp:
    build: ./ftp
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    command: /usr/sbin/pure-ftpd -l puredb:/etc/pure-ftpd/passwd -E -j -R