services:
  apache:
    build: apache/
    ports:
      - "8080:80"
    volumes:
      - ./apache/sites:/usr/local/apache2/htdocs

  nginx:
    build: nginx/
    ports:
      - "80:80"
    volumes:
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled