services:
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./apache/sites:/var/www/html:ro
    ports:
      - "80:80"
    depends_on:
      - apache

  apache:
    build: ./apache
    volumes:
      - ./apache/sites:/var/www/html
    expose:
      - "80"

  ftp:
    build: ./ftp
    volumes:
      - ./apache/sites:/var/www/html
    environment:
      FTP_USER: "ftpuser"
      FTP_PASS: "ftp_password"
    ports:
      - "21:21"