services:
  nginx:
    build: ./nginx
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet

  ftp:
    build: ./ftp
    container_name: ftp-server
    environment:
      - FTP_USER=user
      - FTP_PASS=pass
    ports:
      - "21:21"
    volumes:
      - ./data/ftp:/home/ftpusers
    networks:
      - webnet

networks:
  webnet:
    driver: bridge