services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - apache

  apache:
    build: ./apache
    volumes:
      - ./sites:/var/www/html

  ftp:
    build: ./ftp
    volumes:
      - ./sites:/home/vsftpd
    environment:
      - FTP_USER=user
      - FTP_PASS=pass
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    ports:
      - "21:21"
      - "21100-21110:21100-21110"