version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - apache
    volumes:
      - nginx-data:/etc/nginx/conf.d

  apache:
    build: ./apache
    container_name: apache
    volumes:
      - apache-data:/usr/local/apache2/htdocs

  ftp:
    build: ./ftp
    container_name: ftp
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    command: /usr/sbin/pure-ftpd -l puredb:/etc/pure-ftpd/passwd -E -j -R
    volumes:
      - ftp-data:/home/ftpusers

volumes:
  nginx-data:
  apache-data:
  ftp-data: