services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - apache
    volumes:
      - nginx-data:/etc/nginx/conf.d
      - apache-data:/var/www/html:ro
    networks:
      - webnet

  apache:
    build: ./apache
    container_name: apache
    volumes:
      - apache-data:/usr/local/apache2/htdocs
    networks:
      - webnet

  ftp:
    image: fauria/vsftpd
    container_name: ftp
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      - FTP_USER=test
      - FTP_PASS=test
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=30000
      - PASV_MAX_PORT=30009
      - XFERLOG_STD_FORMAT=NO # Optional, set to YES if needed
    volumes:
      - ftp-data:/home/vsftpd
      - apache-data:/var/www/html:rw # Ensure path consistency
    networks:
      - webnet

volumes:
  nginx-data:
  apache-data:
  ftp-data:

networks:
  webnet: