services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - apache
    volumes:
      - nginx-data:/etc/nginx/conf.d
      - apache-data:/var/www:ro
    networks:
      - webnet

  apache:
    build: ./apache
    container_name: apache
    volumes:
      - apache-data:/usr/local/apache2/htdocs
    networks:
      - webnet

volumes:
  nginx-data:
  apache-data:

networks:
  webnet: